import { 
  BotConfig, 
  BotCommand, 
  WelcomeConfig, 
  TicketConfig, 
  StaffAppConfig, 
  SecurityConfig, 
  RulesConfig, 
  LeaveResignationConfig,
  SuggestionConfig,
  ReportConfig,
  WarningConfig,
  AutoResponseConfig,
  GiveawayConfig,
  LevelConfig,
  ReactionRolesConfig,
  VoiceStatsConfig
} from "../types";

export interface GeneratedProject {
  filename: string;
  content: string;
  language: string;
}

export function generateProjectFiles(
  config: BotConfig,
  commands: BotCommand[],
  welcome?: WelcomeConfig,
  ticket?: TicketConfig,
  staffApp?: StaffAppConfig,
  security?: SecurityConfig,
  rulesBot?: RulesConfig,
  leaveConfig?: LeaveResignationConfig,
  suggestion?: SuggestionConfig,
  report?: ReportConfig,
  warning?: WarningConfig,
  autoResponse?: AutoResponseConfig,
  giveaway?: GiveawayConfig,
  levelConfig?: LevelConfig,
  reactionRoles?: ReactionRolesConfig,
  voiceStats?: VoiceStatsConfig
): GeneratedProject[] {
  const cleanBotName = config.name.toLowerCase().replace(/[^a-z0-9]/g, "-") || "discord-bot";

  // 1. package.json
  const packageJson = {
    name: cleanBotName,
    version: "1.2.0",
    description: `Production bundle for ${config.name} with advanced administrative systems - generated by Discord Bot Builder`,
    main: "index.js",
    scripts: {
      "start": "node index.js",
      "deploy": "node deploy-commands.js"
    },
    dependencies: {
      "discord.js": "^14.14.1",
      "dotenv": "^16.4.5",
      "@google/genai": "^2.4.0"
    },
    engines: {
      "node": ">=16.9.0"
    }
  };

  // 2. .env file template
  const dotenvContent = `# Discord Bot API Credentials
# Obtain these credentials from the: https://discord.com/developers/applications
DISCORD_TOKEN="YOUR_BOT_TOKEN_HERE"
CLIENT_ID="YOUR_CLIENT_ID_HERE"

# Gemini API Key (Required for AI chat triggers)
# Obtain this from Google AI Studio: https://aistudio.google.com/
GEMINI_API_KEY=""
`;

  // 2b. config.json
  const configJson = {
    name: config.name,
    prefix: config.prefix,
    status: config.status,
    activityType: config.activityType,
    activityName: config.activityName,
    customStatus: config.customStatus,
    embedColor: config.embedColor || "#5865F2",
    systems: {
      welcome: welcome || { enabled: false },
      ticket: ticket || { enabled: false },
      staffApp: staffApp || { enabled: false },
      security: security || { enabled: false },
      rulesBot: rulesBot || { enabled: false },
      leaveConfig: leaveConfig || { enabled: false },
      suggestion: suggestion || { enabled: false },
      report: report || { enabled: false },
      warning: warning || { enabled: false },
      autoResponse: autoResponse || { enabled: false },
      giveaway: giveaway || { enabled: false },
      levelConfig: levelConfig || { enabled: false },
      reactionRoles: reactionRoles || { enabled: false },
      voiceStats: voiceStats || { enabled: false }
    }
  };

  // 3. deploy-commands.js - include slash command setups for setup systems as well!
  const allSlashCommands = [...commands.filter(cmd => cmd.type === 'slash')];
  
  // Register setup commands only if systems are enabled
  if (ticket?.enabled) {
    allSlashCommands.push({
      id: "setup-ticket-sc",
      trigger: "/setup-tickets",
      type: "slash",
      description: "Spawns the Support Ticket embedded board inside a channel.",
      responseType: "text",
      responseText: ""
    });
  }
  if (staffApp?.enabled) {
    allSlashCommands.push({
      id: "setup-staff-sc",
      trigger: "/setup-staff",
      type: "slash",
      description: "Spawns the Staff recruitment submission board.",
      responseType: "text",
      responseText: ""
    });
  }
  if (security?.enabled && security?.verificationEnabled) {
    allSlashCommands.push({
      id: "setup-verify-sc",
      trigger: "/setup-verify",
      type: "slash",
      description: "Spawns the Security Captcha profile verification card.",
      responseType: "text",
      responseText: ""
    });
  }
  if (rulesBot?.enabled) {
    allSlashCommands.push({
      id: "setup-rules-sc",
      trigger: "/setup-rules",
      type: "slash",
      description: "Spawns the server categorized laws embedded list.",
      responseType: "text",
      responseText: ""
    });
  }
  if (leaveConfig?.enabled) {
    allSlashCommands.push({
      id: "setup-hr-sc",
      trigger: "/setup-hr",
      type: "slash",
      description: "Spawns the HR Leave request dashboard button.",
      responseType: "text",
      responseText: ""
    });
  }
  if (reactionRoles?.enabled) {
    allSlashCommands.push({
      id: "setup-reaction-roles-sc",
      trigger: "/setup-reactionroles",
      type: "slash",
      description: "Spawns the roles selection buttons board inside a channel.",
      responseType: "text",
      responseText: ""
    });
  }

  const deployCommandsJs = `const { REST, Routes, SlashCommandBuilder } = require('discord.js');
require('dotenv').config();

const commands = [
${allSlashCommands
  .map(cmd => {
    const cleanName = cmd.trigger.replace('/', '').toLowerCase().trim();
    return `  new SlashCommandBuilder()
    .setName('${cleanName}')
    .setDescription('${cmd.description || 'Custom command built using Bot Studio'}')`;
  })
  .join(',\n')}
].map(command => command.toJSON());

const rest = new REST({ version: '10' }).setToken(process.env.DISCORD_TOKEN);

(async () => {
  try {
    console.log('Started refreshing ' + commands.length + ' application (/) commands.');

    if (!process.env.CLIENT_ID) {
      throw new Error("CLIENT_ID environment variable is missing in your .env file!");
    }

    await rest.put(
      Routes.applicationCommands(process.env.CLIENT_ID),
      { body: commands },
    );

    console.log('Successfully reloaded application (/) commands.');
  } catch (error) {
    console.error('Error deploying custom slash commands:', error);
  }
})();
`;

  // Helper inside index.js to handle visual embeds
  const generateEmbedCode = (cmd: BotCommand) => {
    const fieldsCode = cmd.embedFields && cmd.embedFields.length > 0
      ? `,
      fields: [
        ${cmd.embedFields.map(f => `{ name: '${f.name}', value: '${f.value}', inline: ${f.inline} }`).join(',\n        ')}
      ]`
      : '';
      
    return `const embed = {
      title: \`${cmd.embedTitle || ''}\`,
      description: \`${cmd.embedDescription || ''}\`,
      color: parseColor(\`${cmd.embedColor || config.embedColor || '#5865F2'}\`, 5793266),
      ${cmd.embedThumbnail ? `thumbnail: { url: \`${cmd.embedThumbnail}\` },` : ''}
      ${cmd.embedImage ? `image: { url: \`${cmd.embedImage}\` },` : ''}
      ${cmd.embedFooter ? `footer: { text: \`${cmd.embedFooter}\` },` : ''}
      timestamp: new Date().toISOString()${fieldsCode}
    };`;
  };

  // Helper inside index.js to replace state variables
  const placeholderReplacementsHead = `
// Helper to replace custom visual dynamic parameters
function renderPlaceholders(text, messageOrInteraction, isInteraction = false) {
  if (!text) return "";
  const user = isInteraction ? messageOrInteraction.user : messageOrInteraction.author;
  const channel = messageOrInteraction.channel;
  const guild = messageOrInteraction.guild;
  
  return text
    .replace(/{user}/g, user.toString())
    .replace(/{username}/g, user.username)
    .replace(/{channel}/g, channel ? channel.name : 'dm')
    .replace(/{memberCount}/g, guild ? guild.memberCount.toString() : '1')
    .replace(/{time}/g, new Date().toUTCString());
}

// Helper to retrieve channels by ID or Name (tolerant of tags like <#...>, whitespaces, or channel names)
function getChannel(guild, rawIdOrName) {
  if (!rawIdOrName || !guild) return null;
  const clean = rawIdOrName.toString().trim().replace(/[<#>]/g, '').toLowerCase();
  if (!clean) return null;
  
  // 1. Precise ID lookup
  let found = guild.channels.cache.get(clean);
  if (found) return found;
  
  // 2. Exact name lookup
  found = guild.channels.cache.find(c => c.name.toLowerCase() === clean);
  if (found) return found;
  
  // 3. Lenient name lookup (if channel name contains the search term or vice versa)
  found = guild.channels.cache.find(c => c.name.toLowerCase().includes(clean) || clean.includes(c.name.toLowerCase()));
  if (found) return found;

  return null;
}

// Helper to parse hex colors to decimal integers for Discord API Compatibility
function parseColor(colorValue, defaultVal = 3447003) {
  if (!colorValue) return defaultVal;
  if (typeof colorValue === 'number') return colorValue;
  const cleaned = colorValue.toString().replace(/[^0-9a-fA-F]/g, '');
  if (!cleaned) return defaultVal;
  const parsed = parseInt(cleaned, 16);
  return isNaN(parsed) ? defaultVal : parsed;
}

// Helper to validate and format embed banner image URLs safely
function getBanner(url) {
  if (!url || typeof url !== 'string') return undefined;
  const trimmed = url.trim();
  if (trimmed.startsWith('http://') || trimmed.startsWith('https://')) {
    return { url: trimmed };
  }
  return undefined;
}
`;

  const requiresAi = commands.some(cmd => cmd.responseType === 'ai');

  // 4. index.js content (incorporates Welcomer, Support Tickets, Modals, Rules, Leave HR, Security automod!)
  const indexJs = `const { 
  Client, 
  GatewayIntentBits, 
  EmbedBuilder, 
  ActionRowBuilder, 
  ButtonBuilder, 
  ButtonStyle, 
  ModalBuilder, 
  TextInputBuilder, 
  TextInputStyle,
  PermissionFlagsBits
} = require('discord.js');
require('dotenv').config();
const config = require('./config.json');

${requiresAi ? `const { GoogleGenAI } = require('@google/genai');
let ai = null;
if (process.env.GEMINI_API_KEY) {
  ai = new GoogleGenAI({ apiKey: process.env.GEMINI_API_KEY });
} else {
  console.warn("⚠️ GEMINI_API_KEY environment variable is blank. AI commands will fallback to static reminders.");
}
` : ''}

const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent,
    GatewayIntentBits.GuildMembers,
    GatewayIntentBits.GuildPresences
  ]
});

// Cache for anti-spam protection and database-free leveling systems
const messageTimestamps = new Map();
const userXpCache = new Map(); // userId => { xp: number, level: number, lastMessageTimestamp: number }

${placeholderReplacementsHead}

// Client boot ready indicators
client.once('ready', () => {
  console.log(\`Logged in securely as \${client.user.tag}!\`);
  
  // Apply bot customized activity status configurations
  const activityMap = {
    'PLAYING': 0,
    'STREAMING': 1,
    'LISTENING': 2,
    'WATCHING': 3
  };
  
  client.user.setPresence({
    activities: [{ 
      name: config.activityName || "with developers!", 
      type: activityMap[config.activityType] || 0
    }],
    status: config.status || 'online'
  });
});

// Event Handler: Advanced Member Welcomer
client.on('guildMemberAdd', async (member) => {
  const welcome = config.systems.welcome;
  if (!welcome || !welcome.enabled) return;

  try {
    const channel = getChannel(member.guild, welcome.channelId);
    if (channel) {
      // Processes placeholders for Title and Message Text
      const processedTitle = (welcome.welcomeTitle || "Welcome {username}")
        .replace(/{user}/g, member.toString())
        .replace(/{username}/g, member.user.username)
        .replace(/{memberCount}/g, member.guild.memberCount.toString());

      const processedMessage = (welcome.welcomeMessage || "Welcome {user}!")
        .replace(/{user}/g, member.toString())
        .replace(/{username}/g, member.user.username)
        .replace(/{memberCount}/g, member.guild.memberCount.toString());

      const welcomeEmbed = {
        title: processedTitle,
        description: processedMessage,
        color: 5793266, // Blurple
        thumbnail: { url: member.user.displayAvatarURL() },
        image: welcome.bannerUrl ? { url: welcome.bannerUrl } : null,
        footer: { text: \`Member #\${member.guild.memberCount} • \${welcome.botName || "Welcome System"}\` },
        timestamp: new Date().toISOString()
      };

      await channel.send({ content: member.toString(), embeds: [welcomeEmbed] });
    }

    // Handles private Direct Message reception if active
    if (welcome.dmGreeting && welcome.dmMessage) {
      const processedDm = welcome.dmMessage
        .replace(/{user}/g, member.toString())
        .replace(/{username}/g, member.user.username)
        .replace(/{memberCount}/g, member.guild.memberCount.toString());

      await member.send({ content: processedDm }).catch(() => {
        console.warn(\`⚠️ Unreachable DMs: Could not deliver greeting letter to \${member.user.tag}.\`);
      });
    }
  } catch (err) {
    console.error("Error processing Welcomer event:", err);
  }
});

// Event Handler: Messages, Word Filters, AntiSpam & Commands
client.on('messageCreate', async (message) => {
  // Ignore bots and DM conversations
  if (message.author.bot || !message.guild) return;

  const content = message.content.trim();
  const prefix = config.prefix || '!';

  // A. Suggestions System Message-Level Handler
  const suggestion = config.systems.suggestion;
  const cleanSugId = suggestion && suggestion.channelId ? suggestion.channelId.toString().trim().replace(/[<#>]/g, '').toLowerCase() : null;
  const isSuggestionsChannel = suggestion && suggestion.enabled && cleanSugId && (
    message.channel.id === cleanSugId ||
    message.channel.name.toLowerCase() === cleanSugId ||
    message.channel.name.toLowerCase().includes(cleanSugId) ||
    cleanSugId.includes(message.channel.name.toLowerCase())
  );
  if (isSuggestionsChannel) {
    try {
      await message.delete().catch(() => {});
      const suggestEmbed = {
        title: "💡 اقتراح جديد | New Suggestion",
        description: content,
        color: parseColor(suggestion.embedColor, 15859727),
        author: {
          name: suggestion.anonymous ? "عضو مساهم | Anonymous Member" : message.author.tag,
          icon_url: suggestion.anonymous ? null : message.author.displayAvatarURL()
        },
        footer: { text: suggestion.botName || "Suggestions Bot" },
        timestamp: new Date().toISOString()
      };
      const bannerObj = getBanner(suggestion.bannerUrl);
      if (bannerObj) {
        suggestEmbed.image = bannerObj;
      }
      const sentMsg = await message.channel.send({ embeds: [suggestEmbed] });
      if (suggestion.autoReact) {
        await sentMsg.react('👍').catch(() => {});
        await sentMsg.react('👎').catch(() => {});
      }
      return;
    } catch (err) {
      console.error("Error creating suggestion:", err);
    }
  }

  // 1. Guard System: Automod, Swear Filters, Link Filters, AntiSpam
  const security = config.systems.security;
  if (security && security.enabled) {
    
    // AntiSpam Controller
    if (security.spamProtectionEnabled) {
      const now = Date.now();
      const userLogs = messageTimestamps.get(message.author.id) || [];
      // filter messages sent in last 60 seconds
      const recentLogs = userLogs.filter(ts => now - ts < 60000);
      recentLogs.push(now);
      messageTimestamps.set(message.author.id, recentLogs);

      const maxLimit = security.maxMessagesPerMinute || 6;
      if (recentLogs.length > maxLimit) {
        await message.delete().catch(() => {});
        message.channel.send(\`⚠️ \${message.author} يرجى التوقف عن السبام وتكرار الرسائل! (Anti-Spam active)\`).then(m => setTimeout(() => m.delete().catch(() => {}), 5000));
        
        // Log to Guard channel
        if (security.logsChannelId) {
          const logChan = getChannel(message.guild, security.logsChannelId);
          if (logChan) {
            logChan.send({
              embeds: [{
                title: "🚨 تحذير نظام السيكيورتي: سبام مفرط",
                description: \`العضو \${message.author} (\${message.author.tag}) تجاوز حد الإرسال مع تصفية رسالته المزعجة.\`,
                color: 15158332,
                timestamp: new Date().toISOString()
              }]
            }).catch(() => {});
          }
        }
        return;
      }
    }

    // Word swearing content filter
    if (security.wordFilterEnabled && security.badWordsList && security.badWordsList.length > 0) {
      const containsBadWord = security.badWordsList.some(badWord => {
        const regex = new RegExp(\`\\\\\\\\b\${badWord}\\\\\\\\b\`, 'i');
        return regex.test(content) || content.toLowerCase().includes(badWord.toLowerCase());
      });

      if (containsBadWord) {
        await message.delete().catch(() => {});
        message.channel.send(\`⚠️ \${message.author} يُمنع استخدام الكلمات النابية والشتائم داخل هذا السيرفر!\`).then(m => setTimeout(() => m.delete().catch(() => {}), 5000));
        
        if (security.logsChannelId) {
          const logChan = getChannel(message.guild, security.logsChannelId);
          if (logChan) {
            logChan.send({
              embeds: [{
                title: "🚨 تصفية جمل بذيئة",
                description: \`مستند المخالفات: حذف رسالة تحتوي على عبارات ممنوعة من العضو \${message.author} (\${message.author.tag})\`,
                fields: [{ name: "محتوى الرسالة الأصلي", value: content }],
                color: 15158332,
                timestamp: new Date().toISOString()
              }]
            }).catch(() => {});
          }
        }
        return;
      }
    }

    // External link advertising filter
    if (security.linkFilterEnabled) {
      const linkRegex = /(https?:\/\/|discord\.gg\/)/i;
      const isAdmin = message.member.permissions.has(PermissionFlagsBits.Administrator);
      if (linkRegex.test(content) && !isAdmin) {
        await message.delete().catch(() => {});
        message.channel.send(\`⚠️ \${message.author} يُمنع نشر الروابط الخارجية أو الدعوات الإعلانية هنا!\`).then(m => setTimeout(() => m.delete().catch(() => {}), 5000));
        
        if (security.logsChannelId) {
          const logChan = getChannel(message.guild, security.logsChannelId);
          if (logChan) {
            logChan.send({
              embeds: [{
                title: "🚨 حماية الروابط والدعايات",
                description: \`تم حذف رابط غير مصرح به من العضو \${message.author} (\${message.author.tag}).\`,
                fields: [{ name: "رابط المخالفة المكتوب", value: content }],
                color: 15158332,
                timestamp: new Date().toISOString()
              }]
            }).catch(() => {});
          }
        }
        return;
      }
    }
  }

  // B. Auto-Responses System
  const autoRespConfig = config.systems.autoResponse;
  if (autoRespConfig && autoRespConfig.enabled && autoRespConfig.responses && autoRespConfig.responses.length > 0) {
    const matched = autoRespConfig.responses.find(r => {
      const clTrigger = r.trigger.trim().toLowerCase();
      const clContent = content.toLowerCase();
      if (r.matchType === 'exact') {
        return clContent === clTrigger;
      } else {
        return clContent.includes(clTrigger);
      }
    });

    if (matched) {
      const responseText = renderPlaceholders(matched.response, message, false);
      try {
        await message.reply({ content: responseText });
        return;
      } catch (err) {
        console.error("AutoResponse error:", err);
      }
    }
  }

  // C. Leveling XP increment system
  const lv = config.systems.levelConfig;
  if (lv && lv.enabled) {
    const userId = message.author.id;
    const now = Date.now();
    const userData = userXpCache.get(userId) || { xp: 0, level: 1, lastMessageTimestamp: 0 };

    // 60 seconds cooldown
    if (now - userData.lastMessageTimestamp > 60000) {
      userData.xp += lv.xpPerMessage || 15;
      userData.lastMessageTimestamp = now;

      const xpNeededForNext = userData.level * userData.level * 100;
      if (userData.xp >= xpNeededForNext) {
        userData.level += 1;
        const msgStr = (lv.levelUpMessage || "🎉 مبروك يا {user} لقد ارتفع مستواك إلى المستوى **{level}**!")
          .replace(/{user}/g, message.author.toString())
          .replace(/{username}/g, message.author.username)
          .replace(/{level}/g, userData.level.toString());

        const levelUpChannel = getChannel(message.guild, lv.levelUpChannelId) || message.channel;
        if (levelUpChannel) {
          levelUpChannel.send({ content: msgStr }).catch(() => {});
        }

        // Apply Level Role Rewards
        if (lv.roleRewards && lv.roleRewards.length > 0) {
          const matchingRewards = lv.roleRewards.filter(r => r.level <= userData.level);
          for (const reward of matchingRewards) {
            const role = message.guild.roles.cache.get(reward.id) || 
                         message.guild.roles.cache.find(r => r.name.toLowerCase() === reward.roleName.toLowerCase() || r.id === reward.id);
            if (role) {
              await message.member.roles.add(role).catch(() => {});
            }
          }
        }
      }
      userXpCache.set(userId, userData);
    }
  }

  // Prefix Command Extraction block
  if (!content.startsWith(prefix)) return;
  const args = content.slice(prefix.length).trim().split(/ +/);
  const commandName = args.shift().toLowerCase();

  // Unified setups prefix triggers as a fallback setup channel helper
  if (commandName === 'setup-tickets' && config.systems.ticket.enabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const ticket = config.systems.ticket;
    const row = new ActionRowBuilder().addComponents(
      new ButtonBuilder()
        .setCustomId('open_ticket')
        .setLabel(ticket.buttonLabel || 'فتح تذكرة | Open Ticket 📩')
        .setStyle(ButtonStyle.Primary)
    );
    await message.channel.send({
      embeds: [{
        title: ticket.panelTitle || "🎫 نظام فتح التذاكر",
        description: ticket.panelDescription || "اضغط على الزر أدناه للتحدث مع الطاقم الإداري مباشرة.",
        color: parseColor(ticket.embedColor, 3447003),
        image: ticket.bannerUrl ? { url: ticket.bannerUrl } : undefined,
        footer: { text: ticket.botName || "Support Service" }
      }],
      components: [row]
    });
    return;
  }

  if (commandName === 'setup-staff' && config.systems.staffApp.enabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const staffApp = config.systems.staffApp;
    const row = new ActionRowBuilder().addComponents(
      new ButtonBuilder()
        .setCustomId('apply_staff')
        .setLabel('تقديم على الإدارة 🛡️ Apply for Staff')
        .setStyle(ButtonStyle.Success)
    );
    await message.channel.send({
      embeds: [{
        title: "🛡️ تقديم طلبات الانضمام لطاقم الإدارة",
        description: "إذا كنت تجد في نفسك الكفاءة، الخبرة والالتزام لمساعدتنا في تنظيم شؤون السيرفر، يرجى الضغط على زر التقديم والإجابة على الاستبيان.",
        color: parseColor(staffApp.embedColor, 3066993),
        image: staffApp.bannerUrl ? { url: staffApp.bannerUrl } : undefined,
        footer: { text: staffApp.botName || "Recruiting Bot" }
      }],
      components: [row]
    });
    return;
  }

  if (commandName === 'setup-verify' && config.systems.security.enabled && config.systems.security.verificationEnabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const sec = config.systems.security;
    const row = new ActionRowBuilder().addComponents(
      new ButtonBuilder()
        .setCustomId('verify_user')
        .setLabel(sec.verificationButtonLabel || 'تفعيل الحساب (Verify Profile) ✅')
        .setStyle(ButtonStyle.Success)
    );
    await message.channel.send({
      embeds: [{
        title: "🔐 بوابة التحقق البشري الآمن (Server Verification Gate)",
        description: "أهلاً بك في حماية السيرفر! لمنع دخول الحسابات الوهمية والسبام بوتس، من فضلك اضغط على زر تفعيل وتأكيد الحماية لتتمكن من الوصول لباقي القنوات والمحادثة أونلاين.",
        color: parseColor(sec.embedColor, 15105570),
        image: sec.bannerUrl ? { url: sec.bannerUrl } : undefined
      }],
      components: [row]
    });
    return;
  }

  if (commandName === 'setup-rules' && config.systems.rulesBot.enabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const rulesBot = config.systems.rulesBot;
    
    for (const cat of rulesBot.categories) {
      const formattedRules = cat.rules.map((r, idx) => \`**[\${idx + 1}]** \${r}\`).join('\\n\\n');
      await message.channel.send({
        embeds: [{
          title: \`\${cat.icon} \${cat.name}\`,
          description: formattedRules || "لا توجد لوائح قوانين مضافة حالياً.",
          color: parseColor(rulesBot.embedColor, 10181046),
          image: rulesBot.bannerUrl ? { url: rulesBot.bannerUrl } : undefined,
          footer: { text: rulesBot.botName || "System rules bot" }
        }]
      });
    }
    return;
  }

  if (commandName === 'setup-hr' && config.systems.leaveConfig.enabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const leave = config.systems.leaveConfig;
    const row = new ActionRowBuilder().addComponents(
      new ButtonBuilder()
        .setCustomId('hr_apply_leave')
        .setLabel('طلب إجازة مؤقتة 🌴')
        .setStyle(ButtonStyle.Primary),
      new ButtonBuilder()
        .setCustomId('hr_apply_resignation')
        .setLabel('تقديم طلب الاستقالة 🚪')
        .setStyle(ButtonStyle.Danger)
    );
    await message.channel.send({
      embeds: [{
        title: "🌴 شؤون الموظفين والإجازات والاستقالات",
        description: "خاص بتقديم رغبات الإجازات المؤقتة أو تقديم طلبات الاستقالة الرسمية كعضو في الإدارة. انقر فوق الزر المناسب للبدء.",
        color: parseColor(leave.embedColor, 3066993),
        image: leave.bannerUrl ? { url: leave.bannerUrl } : undefined
      }],
      components: [row]
    });
    return;
  }

  if (commandName === 'setup-reactionroles' && config.systems.reactionRoles.enabled) {
    if (!message.member.permissions.has(PermissionFlagsBits.Administrator)) return;
    const rx = config.systems.reactionRoles;
    const buttons = rx.rolesList.map(r => {
      const styleMap = {
        'blue': ButtonStyle.Primary,
        'gray': ButtonStyle.Secondary,
        'green': ButtonStyle.Success,
        'red': ButtonStyle.Danger,
        'yellow': ButtonStyle.Secondary
      };
      return new ButtonBuilder()
        .setCustomId(\`rx_role_\${r.id}\`)
        .setLabel(\`\${r.emoji || ''} \${r.label}\`)
        .setStyle(styleMap[r.color] || ButtonStyle.Primary);
    });

    const rows = [];
    for (let i = 0; i < buttons.length; i += 5) {
      rows.push(new ActionRowBuilder().addComponents(buttons.slice(i, i + 5)));
    }

    await message.channel.send({
      embeds: [{
        title: rx.panelTitle || "🎭 لوحة اختيار الرتب التفاعلية",
        description: rx.panelDescription || "اختر رتبتك بنفسك عبر الضغط على الأزرار التفاعلية بالأسفل للحصول على الصلاحيات فورياً!",
        color: parseColor(rx.embedColor, 15277667),
        image: rx.bannerUrl ? { url: rx.bannerUrl } : undefined,
        footer: { text: rx.botName || "Reaction Roles Helper" }
      }],
      components: rows
    });
    return;
  }

  if (commandName === 'rank' || commandName === 'level') {
    const leveling = config.systems.levelConfig;
    if (leveling && leveling.enabled) {
      const userData = userXpCache.get(message.author.id) || { xp: 0, level: 1 };
      const xpNeeded = userData.level * userData.level * 100;
      await message.reply({
        content: \`📊 **رتبتك ومستواك الحالي:**\\n\\n• المستوى: \\\`\${userData.level}\\\`\\n• نقاط الخبرة (XP): \\\`\${userData.xp}/\${xpNeeded}\\\`\`
      }).catch(() => {});
      return;
    }
  }


  // Standard User Built Prefix command routing
${commands
  .filter(cmd => cmd.type === 'prefix')
  .map(cmd => {
    const trigger = cmd.trigger.toLowerCase().trim();
    let handlerBody = '';
    
    if (cmd.responseType === 'text') {
      handlerBody = `    const response = renderPlaceholders(\`${cmd.responseText}\`, message, false);
    return message.channel.send(response);`;
    } else if (cmd.responseType === 'embed') {
      handlerBody = `    ${generateEmbedCode(cmd)}
    // Render placeholders inside embed fields before dispatching
    if (embed.title) embed.title = renderPlaceholders(embed.title, message, false);
    if (embed.description) embed.description = renderPlaceholders(embed.description, message, false);
    if (embed.fields) {
      embed.fields = embed.fields.map(f => ({
        name: renderPlaceholders(f.name, message, false),
        value: renderPlaceholders(f.value, message, false),
        inline: f.inline
      }));
    }
    return message.channel.send({ embeds: [embed] });`;
    } else if (cmd.responseType === 'ai') {
      handlerBody = `    if (!ai) {
      return message.channel.send("🤖 AI system is offline. Please make sure GEMINI_API_KEY is configured in my environment.");
    }
    await message.channel.sendTyping();
    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: \`Act as custom Discord bot. Prompt personality instruction: "${cmd.responseText}". Respond to this user text in a natural, funny Discord chat style: "\${content}"\`,
      });
      return message.channel.send(response.text || "I was unable to gather thoughts.");
    } catch (err) {
      console.error(err);
      return message.channel.send("❌ Error connecting to Gemini mental core.");
    }`;
    }

    return `  if (commandName === '${trigger}') {
${handlerBody}
  }`;
  })
  .join('\n')}
});

// Event Handler: Custom Slash command routing + Support ticket button & Recruitment interactions
client.on('interactionCreate', async (interaction) => {
  if (interaction.isChatInputCommand()) {
    const { commandName } = interaction;

    // Interactive systems setup commands for Slash trigger support
    if (commandName === 'setup-tickets' && config.systems.ticket.enabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
        return interaction.reply({ content: "❌ عذراً، لا تمتلك صلاحيات كافية لإدارة وإعداد هذا نظام.", ephemeral: true });
      }
      const ticket = config.systems.ticket;
      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId('open_ticket')
          .setLabel(ticket.buttonLabel || 'فتح تذكرة | Open Ticket 📩')
          .setStyle(ButtonStyle.Primary)
      );
      await interaction.reply({
        embeds: [{
          title: ticket.panelTitle || "🎫 نظام فتح التذاكر",
          description: ticket.panelDescription || "اضغط على الزر أدناه للتحدث مع الطاقم الإداري مباشرة.",
          color: parseColor(ticket.embedColor, 3447003),
          image: ticket.bannerUrl ? { url: ticket.bannerUrl } : undefined,
          footer: { text: ticket.botName || "Support Service" }
        }],
        components: [row]
      });
      return;
    }

    if (commandName === 'setup-staff' && config.systems.staffApp.enabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) return;
      const staffApp = config.systems.staffApp;
      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId('apply_staff')
          .setLabel('تقديم على الإدارة 🛡️ Apply for Staff')
          .setStyle(ButtonStyle.Success)
      );
      await interaction.reply({
        embeds: [{
          title: "🛡️ تقديم طلبات الانضمام لطاقم الإدارة",
          description: "إذا كنت تجد في نفسك الكفاءة والالتزام, يرجى الضغط على زر التقديم والإجابة على الاستبيان.",
          color: parseColor(staffApp.embedColor, 3066993),
          image: staffApp.bannerUrl ? { url: staffApp.bannerUrl } : undefined,
          footer: { text: staffApp.botName || "Recruiting Bot" }
        }],
        components: [row]
      });
      return;
    }

    if (commandName === 'setup-verify' && config.systems.security.enabled && config.systems.security.verificationEnabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) return;
      const sec = config.systems.security;
      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId('verify_user')
          .setLabel(sec.verificationButtonLabel || 'تفعيل الحساب (Verify Profile) ✅')
          .setStyle(ButtonStyle.Success)
      );
      await interaction.reply({
        embeds: [{
          title: "🔐 بوابة التحقق البشري الآمن (Server Verification Gate)",
          description: "اضغط على زر التفعيل لتأكيد حمايتك ومنحك الرتبة تلقائياً.",
          color: parseColor(sec.embedColor, 15105570),
          image: sec.bannerUrl ? { url: sec.bannerUrl } : undefined
        }],
        components: [row]
      });
      return;
    }

    if (commandName === 'setup-rules' && config.systems.rulesBot.enabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) return;
      const rulesBot = config.systems.rulesBot;
      await interaction.reply({ content: "💡 جاري بث وطباعة لوحة القوانين بالكامل...", ephemeral: true });
      
      for (const cat of rulesBot.categories) {
        const formattedRules = cat.rules.map((r, idx) => \`**[\${idx + 1}]** \${r}\`).join('\\n\\n');
        await interaction.channel.send({
          embeds: [{
            title: \`\${cat.icon} \${cat.name}\`,
            description: formattedRules || "لا توجد لوائح قوانين مضافة حالياً.",
            color: parseColor(rulesBot.embedColor, 10181046),
            image: rulesBot.bannerUrl ? { url: rulesBot.bannerUrl } : undefined,
            footer: { text: rulesBot.botName || "System rules bot" }
          }]
        });
      }
      return;
    }

    if (commandName === 'setup-hr' && config.systems.leaveConfig.enabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) return;
      const leave = config.systems.leaveConfig;
      const row = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId('hr_apply_leave')
          .setLabel('طلب إجازة مؤقتة 🌴')
          .setStyle(ButtonStyle.Primary),
        new ButtonBuilder()
          .setCustomId('hr_apply_resignation')
          .setLabel('تقديم طلب الاستقالة 🚪')
          .setStyle(ButtonStyle.Danger)
      );
      await interaction.reply({
        embeds: [{
          title: "🌴 شؤون الموظفين والإجازات والاستقالات",
          description: "خاص بتقديم رغبات الإجازات المؤقتة أو تقديم طلبات الاستقالة الرسمية كعضو في الإدارة. انقر فوق الزر المناسب للبدء.",
          color: parseColor(leave.embedColor, 3066993),
          image: leave.bannerUrl ? { url: leave.bannerUrl } : undefined
        }],
        components: [row]
      });
      return;
    }

    if (commandName === 'setup-reactionroles' && config.systems.reactionRoles.enabled) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
        return interaction.reply({ content: "❌ عذراً، لا تمتلك صلاحيات كافية لإعداد الكبسات ورتب التفاعل.", ephemeral: true });
      }
      const rx = config.systems.reactionRoles;
      const buttons = rx.rolesList.map(r => {
        const styleMap = {
          'blue': ButtonStyle.Primary,
          'gray': ButtonStyle.Secondary,
          'green': ButtonStyle.Success,
          'red': ButtonStyle.Danger,
          'yellow': ButtonStyle.Secondary
        };
        return new ButtonBuilder()
          .setCustomId(\`rx_role_\${r.id}\`)
          .setLabel(\`\${r.emoji || ''} \${r.label}\`)
          .setStyle(styleMap[r.color] || ButtonStyle.Primary);
      });

      const rows = [];
      for (let i = 0; i < buttons.length; i += 5) {
        rows.push(new ActionRowBuilder().addComponents(buttons.slice(i, i + 5)));
      }

      await interaction.reply({ content: "✅ تم تهيئة ونشر لوحة اختيار الأدوار بالأسفل بنجاح!", ephemeral: true });
      await interaction.channel.send({
        embeds: [{
          title: rx.panelTitle || "🎭 لوحة اختيار الرتب التفاعلية",
          description: rx.panelDescription || "اختر رتبتك بنفسك عبر الضغط على الأزرار التفاعلية بالأسفل للحصول على الصلاحيات فورياً!",
          color: parseColor(rx.embedColor, 15277667),
          image: rx.bannerUrl ? { url: rx.bannerUrl } : undefined,
          footer: { text: rx.botName || "Reaction Roles Helper" }
        }],
        components: rows
      });
      return;
    }

    // Standard User Designed Slash Command executing paths
${commands
  .filter(cmd => cmd.type === 'slash')
  .map(cmd => {
    const trigger = cmd.trigger.replace('/', '').toLowerCase().trim();
    let handlerBody = '';
    
    if (cmd.responseType === 'text') {
      handlerBody = `    const response = renderPlaceholders(\`${cmd.responseText}\`, interaction, true);
    return interaction.reply({ content: response });`;
    } else if (cmd.responseType === 'embed') {
      handlerBody = `    ${generateEmbedCode(cmd)}
    // Render placeholders inside embed fields before dispatching
    if (embed.title) embed.title = renderPlaceholders(embed.title, interaction, true);
    if (embed.description) embed.description = renderPlaceholders(embed.description, interaction, true);
    if (embed.fields) {
      embed.fields = embed.fields.map(f => ({
        name: renderPlaceholders(f.name, interaction, true),
        value: renderPlaceholders(f.value, interaction, true),
        inline: f.inline
      }));
    }
    return interaction.reply({ embeds: [embed] });`;
    } else if (cmd.responseType === 'ai') {
      handlerBody = `    if (!ai) {
      return interaction.reply({ content: "🤖 My AI subroutines are offline! Provide GEMINI_API_KEY inside your host env.", ephemeral: true });
    }
    await interaction.deferReply();
    try {
      const response = await ai.models.generateContent({
        model: "gemini-3.5-flash",
        contents: \`Act as a Discord bot. Personality parameters: "${cmd.responseText}". Reply directly to user ping query: "/\${commandName}"\`,
      });
      return interaction.editReply({ content: response.text || "Cannot query Gemini thoughts right now." });
    } catch (err) {
      console.error(err);
      return interaction.editReply({ content: "❌ Failure linking to my Gemini AI processors." });
    }`;
    }

    return `    if (commandName === '${trigger}') {
      try {
${handlerBody}
      } catch (err) {
        console.error(err);
        return interaction.reply({ content: "❌ Command execution failure inside index.js log framework.", ephemeral: true }).catch(() => {});
      }
    }`;
  })
  .join('\n')}
  }

  // BUTTON INTERACTION TRIGGERS
  if (interaction.isButton()) {
    const customId = interaction.customId;

    if (customId.startsWith('rx_role_')) {
      await interaction.deferReply({ ephemeral: true });
      const roleId = customId.replace('rx_role_', '');
      const rx = config.systems.reactionRoles;
      if (!rx || !rx.enabled) {
        return interaction.editReply({ content: "⚠️ هذا النظام معطل حالياً." });
      }

      const roleObj = rx.rolesList.find(r => r.id === roleId);
      if (!roleObj) {
        return interaction.editReply({ content: "⚠️ لم أتمكن من العثور على رتبة مطابقة لهذه الكبسة." });
      }

      try {
        let role = interaction.guild.roles.cache.find(r => r.name.toLowerCase() === roleObj.roleName.toLowerCase() || r.id === roleObj.roleName);
        if (!role) {
          role = interaction.guild.roles.cache.find(r => r.name === roleObj.roleName);
        }
        if (!role) {
          role = await interaction.guild.roles.create({
            name: roleObj.roleName,
            color: '#34495e',
            reason: 'Automated Reaction Role generation'
          }).catch(() => null);
        }

        if (role) {
          const hasRole = interaction.member.roles.cache.has(role.id);
          if (hasRole) {
            await interaction.member.roles.remove(role);
            return interaction.editReply({ content: \`✅ تم إزالة الرتبة **\${role.name}** منك بنجاح.\` });
          } else {
            await interaction.member.roles.add(role);
            return interaction.editReply({ content: \`✅ تم منحك الرتبة **\${role.name}** بنجاح!\` });
          }
        } else {
          return interaction.editReply({ content: \`⚠️ لم أتمكن من إيجاد أو إنشاء رتبة باسم "\${roleObj.roleName}".\` });
        }
      } catch (err) {
        console.error("Error giving reaction role:", err);
        return interaction.editReply({ content: "❌ فشلت محاولة تعديل رتبتك. قد تكون رتبة البوت أدنى من الرتبة المراد منحها أو تفتقد للصلاحية." });
      }
    }

    // A. Guard verify profile button
    if (customId === 'verify_user') {
      await interaction.deferReply({ ephemeral: true });
      const sec = config.systems.security;
      try {
        // Grant "Member" or verify role dynamically
        let role = interaction.guild.roles.cache.find(r => r.name.toLowerCase() === 'member' || r.name === 'الأعضاء' || r.name === 'عضو');
        if (!role) {
          // Attempt to build Member role if missing and high perm available
          role = await interaction.guild.roles.create({
            name: 'Member',
            color: '#3498db',
            reason: 'Automated verified member role generation'
          }).catch(() => null);
        }

        if (role) {
          await interaction.member.roles.add(role);
          return interaction.editReply({ content: sec.verificationSuccessMessage || "تهانينا! تم تفعيل حسابك ومنحك الرتبة بنجاح. 🔓" });
        } else {
          return interaction.editReply({ content: "⚠️ لم أستطع العثور على رتبة العضو (Member) لمنحها لك، الرجاء طلب المساعدة من أحد المسؤولين بالسيرفر." });
        }
      } catch (err) {
        console.error("Error verification role add:", err);
        return interaction.editReply({ content: "❌ حدث خطأ داخلي أثناء منح الرتبة. تأكد من رفرفة رتبة البوت بأول القائمة لإعطائه الأولوية العالية." });
      }
    }

    // B. Open Support Ticket
    if (customId === 'open_ticket') {
      await interaction.deferReply({ ephemeral: true });
      const ticket = config.systems.ticket;

      try {
        const openedChanName = \`🎫-تذكرة-\${interaction.user.username.toLowerCase()}\`;
        const alreadyExists = interaction.guild.channels.cache.find(c => c.name === openedChanName);
        if (alreadyExists) {
          return interaction.editReply({ content: \`⚠️ لديك تذكرة دعم فني مفتوحة بالفعل هنا يا بطل: \${alreadyExists}\` });
        }

        // Dynamically create a thread/private channel
        const ticketChannel = await interaction.guild.channels.create({
          name: openedChanName,
          type: 0, // GuildText
          permissionOverwrites: [
            {
              id: interaction.guild.id,
              deny: [PermissionFlagsBits.ViewChannel] // Hide room from everyone
            },
            {
              id: interaction.user.id,
              allow: [
                PermissionFlagsBits.ViewChannel, 
                PermissionFlagsBits.SendMessages, 
                PermissionFlagsBits.EmbedLinks,
                PermissionFlagsBits.ReadMessageHistory
              ] // Let user talk inside
            }
          ]
        });

        const categoryPrefix = ticket.ticketCategoryName || "تذاكر الدعم Open Tickets";
        const category = interaction.guild.channels.cache.find(c => c.name.toLowerCase().includes(categoryPrefix.toLowerCase()) && c.type === 4);
        if (category) {
          await ticketChannel.setParent(category.id, { lockPermissions: false }).catch(() => {});
        }

        const closeRow = new ActionRowBuilder().addComponents(
          new ButtonBuilder()
            .setCustomId('close_ticket')
            .setLabel('إغلاق التذكرة 🔒 Close Ticket')
            .setStyle(ButtonStyle.Danger)
        );

        await ticketChannel.send({
          content: \`\${interaction.user} | @here\`,
          embeds: [{
            title: ticket.panelTitle || "تذكرة الدعم المفتوحة",
            description: \`مرحباً بك يا \${interaction.user}!\\n\\n\${ticket.welcomeMessage || "سيتواصل معك كابتن الإدارة قريباً بمجرد توفره. يرجى توضيح استفسارك."}\`,
            color: 3447003,
            footer: { text: ticket.botName || "Support Ticket Desk" },
            timestamp: new Date().toISOString()
          }],
          components: [closeRow]
        });

        return interaction.editReply({ content: \`✅ تم إنشاء تذكرة الدعم الفني الخاصة بك بنجاح! توجه إليها هنا: \${ticketChannel}\` });
      } catch (err) {
        console.error("Failed ticket generation:", err);
        return interaction.editReply({ content: "❌ لقد فشل إنشاء تذكرة الدعم الفني الخاصة بك. الرجاء التماس صلاحيات البوت الإدارية العليا." });
      }
    }

    // C. Close Support Ticket
    if (customId === 'close_ticket') {
      await interaction.reply({ content: "🔒 جارى إغلاق الغرفة وترشيح القناة للحذف النهائي بعد 5 ثوانٍ..." });
      
      const ticket = config.systems.ticket;
      try {
        if (ticket.logChannelId) {
          const logChan = getChannel(interaction.guild, ticket.logChannelId);
          if (logChan) {
            logChan.send({
              embeds: [{
                title: "📋 أرشيف وإغلاق تذكرة سفر",
                description: \`تم إغلاق التذكرة **\${interaction.channel.name}** نهائياً بواسطة **\${interaction.user.tag}**.\`,
                color: 15158332,
                timestamp: new Date().toISOString()
              }]
            }).catch(() => {});
          }
        }
      } catch (err) {}

      setTimeout(async () => {
        await interaction.channel.delete().catch(() => {});
      }, 5000);
      return;
    }

    // D. Staff applications button launcher
    if (customId === 'apply_staff') {
      const staffApp = config.systems.staffApp;
      if (!staffApp || !staffApp.enabled) {
        return interaction.reply({ content: "⚠️ التقديم مغلق حالياً يا أسد. شكراً لاهتمامك!", ephemeral: true });
      }

      const modal = new ModalBuilder()
        .setCustomId('staff_app_modal')
        .setTitle('طلب الانضمام لطاقم الإدارة 🛡️');

      const rows = [];
      const questionsList = staffApp.questions || [];
      
      if (questionsList.length === 0) {
        return interaction.reply({ content: "⚠️ لم يتم كتابة أسئلة لهذا النموذج.", ephemeral: true });
      }

      questionsList.slice(0, 5).forEach((q, idx) => {
        const input = new TextInputBuilder()
          .setCustomId(\`q_\${idx}\`)
          .setLabel(q.length > 45 ? q.slice(0, 42) + '...' : q)
          .setPlaceholder('اكتب إجابتك هنا بوضوح...')
          .setStyle(TextInputStyle.Paragraph)
          .setRequired(true);

        rows.push(new ActionRowBuilder().addComponents(input));
      });

      modal.addComponents(rows);
      await interaction.showModal(modal);
      return;
    }

    // E. HR Leave request trigger button launcher (Leave)
    if (customId === 'hr_apply_leave') {
      const leave = config.systems.leaveConfig;
      if (!leave || !leave.enabled) {
        return interaction.reply({ content: "⚠️ نظام تقديم الإجازات والاستقالات معطل حالياً.", ephemeral: true });
      }

      const modal = new ModalBuilder()
        .setCustomId('hr_leave_modal')
        .setTitle('تقديم طلب إجازة مؤقتة 🌴');

      const reasonInput = new TextInputBuilder()
        .setCustomId('leave_reason')
        .setLabel('السبب الفعلي والمدة المقترحة للإجازة')
        .setPlaceholder('اكتب الأسباب والظروف والمدة الزمنية بالتفصيل...')
        .setRequired(true)
        .setStyle(TextInputStyle.Paragraph);

        new ActionRowBuilder().addComponents(reasonInput)
      );

      await interaction.showModal(modal);
      return;
    }

    // HR Resignation request trigger button launcher (Resignation)
    if (customId === 'hr_apply_resignation') {
      const leave = config.systems.leaveConfig;
      if (!leave || !leave.enabled) {
        return interaction.reply({ content: "⚠️ نظام تقديم الإجازات والاستقالات معطل حالياً.", ephemeral: true });
      }

      const modal = new ModalBuilder()
        .setCustomId('hr_resignation_modal')
        .setTitle('تقديم طلب الاستقالة الرسمية 🚪');

      const reasonInput = new TextInputBuilder()
        .setCustomId('resignation_reason')
        .setLabel('السبب الفعلي لطلب الاستقالة')
        .setPlaceholder('يرجى كتابة أسباب الاستقالة وتوضيح رغبتك بالتفصيل...')
        .setRequired(true)
        .setStyle(TextInputStyle.Paragraph);

      modal.addComponents(
        new ActionRowBuilder().addComponents(reasonInput)
      );

      await interaction.showModal(modal);
      return;
    }

    // F. HR Petitions approval/rejection button matching
    if (customId.startsWith('hr_approve_') || customId.startsWith('hr_reject_')) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
        return interaction.reply({ content: "❌ لا تمتلك صلاحيات إدارية كافية لتسيير ومعالجة هذا الطلب.", ephemeral: true });
      }

      const isApprove = customId.startsWith('hr_approve_');
      let requestType = 'leave';
      let userId = '';

      if (customId.includes('_leave_')) {
        requestType = 'leave';
        userId = customId.replace(isApprove ? 'hr_approve_leave_' : 'hr_reject_leave_', '');
      } else if (customId.includes('_resignation_')) {
        requestType = 'resignation';
        userId = customId.replace(isApprove ? 'hr_approve_resignation_' : 'hr_reject_resignation_', '');
      } else {
        userId = customId.replace(isApprove ? 'hr_approve_' : 'hr_reject_', '');
      }

      await interaction.deferReply({ ephemeral: true });
      try {
        const targetMember = await interaction.guild.members.fetch(userId).catch(() => null);
        if (targetMember) {
          let letter = '';
          if (requestType === 'leave') {
            letter = isApprove 
              ? "🎉 مرحباً بك! نود إخبارك بأنه تم **الموافقة والاعتماد** على طلب الإجازة الخاص بك بنجاح من شؤون الموظفين."
              : "⚠️ مرحباً بك. للأسف تم **رفض** طلب الإجازة الخاص بك نظراً للحاجة الهامة للعمل في الوقت الراهن.";
            
            // Add leave role if configured
            if (isApprove && config.systems.leaveConfig.leaveRoleId) {
              const role = interaction.guild.roles.cache.get(config.systems.leaveConfig.leaveRoleId) || 
                           interaction.guild.roles.cache.find(r => r.name.toLowerCase() === config.systems.leaveConfig.leaveRoleId.toLowerCase() || r.id === config.systems.leaveConfig.leaveRoleId);
              if (role) {
                await targetMember.roles.add(role).catch(() => {});
              }
            }
          } else {
            letter = isApprove 
              ? "🚪 تم **الموافقة على طلب استقالتك رسميًا** وسحب كافة رتبك وصلاحياتك وتسويه مستحقاتك الإدارية. نشكرك على فترتك وخدمتك."
              : "❌ تم **رفض طلب استقالتك الإدارية**. يرجى مراجعة الإدارة العليا للتفاهم وتسوية الأوضاع بشكل داخلي.";
            
            // Remove resignation roles if configured
            if (isApprove && config.systems.leaveConfig.resignationRemoveRoleIds) {
              const roleIds = config.systems.leaveConfig.resignationRemoveRoleIds.split(',').map(id => id.trim()).filter(Boolean);
              for (const rId of roleIds) {
                const role = interaction.guild.roles.cache.get(rId) || 
                             interaction.guild.roles.cache.find(r => r.name.toLowerCase() === rId.toLowerCase() || r.id === rId);
                if (role) {
                  await targetMember.roles.remove(role).catch(() => {});
                }
              }
            }
          }
          await targetMember.send({ content: letter }).catch(() => {});
        }

        const origEmbed = interaction.message.embeds[0];
        const updatedEmbed = {
          ...origEmbed.toJSON(),
          title: origEmbed.title + (isApprove ? " [مقبولة إدارياً ✅]" : " [مرفوضة إدارياً ❌]"),
          color: isApprove ? 3066993 : 15158332,
          footer: { text: \`تمت المعالجة بواسطة المشرف: \${interaction.user.tag}\` }
        };

        await interaction.message.edit({ embeds: [updatedEmbed], components: [] }).catch(() => {});
        return interaction.editReply({ content: "✅ تم توقيع الوثيقة واعتمادها بالخاص وإعلام السائل." });
      } catch (err) {
        console.error("HR Decision application failure:", err);
        return interaction.editReply({ content: "❌ حدثت مشكلة إدارية أثناء تسيير رغبات المعاهدة." });
      }
    }

    // G. Recruitments candidate approval/rejection button matching
    if (customId.startsWith('staff_approve_') || customId.startsWith('staff_reject_')) {
      if (!interaction.member.permissions.has(PermissionFlagsBits.Administrator)) {
        return interaction.reply({ content: "❌ لا تمتلك صلاحيات كافية لتقرير شأن هذا العضو.", ephemeral: true });
      }

      const isApprove = customId.startsWith('staff_approve_');
      const userId = customId.replace(isApprove ? 'staff_approve_' : 'staff_reject_', '');

      await interaction.deferReply({ ephemeral: true });
      const staffApp = config.systems.staffApp;

      try {
        const targetMember = await interaction.guild.members.fetch(userId).catch(() => null);
        if (targetMember) {
          const template = isApprove 
            ? (staffApp.autoMessageOnApprove || "🎉 Congratulations! Application accepted.")
            : (staffApp.autoMessageOnReject || "Thank you for applying. Rejected.");

          const customizedMsg = template
            .replace(/{user}/g, targetMember.toString())
            .replace(/{username}/g, targetMember.user.username);

          await targetMember.send({ content: customizedMsg }).catch(() => {});

          // Auto-assign role on approval if configured
          if (isApprove && staffApp.approvedRoleId) {
            const role = interaction.guild.roles.cache.get(staffApp.approvedRoleId) || 
                         interaction.guild.roles.cache.find((r: any) => r.name.toLowerCase() === staffApp.approvedRoleId.toLowerCase() || r.id === staffApp.approvedRoleId);
            if (role) {
              await targetMember.roles.add(role).catch(() => {});
            }
          }
        }

        const origEmbed = interaction.message.embeds[0];
        const updatedEmbed = {
          ...origEmbed.toJSON(),
          title: origEmbed.title + (isApprove ? " [تم قبول التقديم ✅]" : " [تم رفض التقديم ❌]"),
          color: isApprove ? 3066993 : 15158332,
          footer: { text: \`المقيّم: \${interaction.user.tag}\` }
        };

        await interaction.message.edit({ embeds: [updatedEmbed], components: [] }).catch(() => {});
        return interaction.editReply({ content: \`✅ تم تحديث كارت التقديم بنجاح وإرسال إشعار للخاص للباحث.\` });
      } catch (err) {
        console.error(err);
        return interaction.editReply({ content: "❌ حدث خطأ داخلي أثناء اعتماد قرار التقديم." });
      }
    }
  }

  // MODAL SUBMISSIONS INTERACTION HANDLER
  if (interaction.type === 5) {
    const modalId = interaction.customId;

    // A. Staff Application modal submission
    if (modalId === 'staff_app_modal') {
      await interaction.deferReply({ ephemeral: true });
      const staffApp = config.systems.staffApp;
      const questionsList = staffApp.questions || [];
      const answers = [];

      questionsList.slice(0, 5).forEach((q, idx) => {
        const valueText = interaction.fields.getTextInputValue(\`q_\${idx}\`);
        answers.push({ question: q, answer: valueText });
      });

      const submissionFields = answers.map((item, idx) => ({
        name: \`📌 \${idx + 1}. \${item.question}\`,
        value: item.answer || 'لم يتم الإجابة',
        inline: false
      }));

      const applicationEmbed = {
        title: "⚡ طلب عضوية جديد طاقم الإدارة",
        description: \`تقدّم السيرة الذاتية بواسطة العضو: \${interaction.user} (\${interaction.user.tag})\\nID: \` + "\`" + interaction.user.id + "\`",
        color: 3447003,
        fields: submissionFields,
        timestamp: new Date().toISOString()
      };

      const judgmentRow = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId(\`staff_approve_\${interaction.user.id}\`)
          .setLabel("قبول التعيين ✅ Approve")
          .setStyle(ButtonStyle.Success),
        new ButtonBuilder()
          .setCustomId(\`staff_reject_\${interaction.user.id}\`)
          .setLabel("رفض التعيين ❌ Reject")
          .setStyle(ButtonStyle.Danger)
      );

      // Search and dispatch to Staff channel
      let auditChan = interaction.guild.channels.cache.find(c => c.name.toLowerCase().includes("تقديمات") || c.name.toLowerCase().includes("staff"));
      if (!auditChan) {
        auditChan = interaction.guild.channels.cache.find(c => c.type === 0); // fallback general
      }

      if (auditChan) {
        await auditChan.send({ embeds: [applicationEmbed], components: [judgmentRow] }).catch(console.error);
      }

      return interaction.editReply({ content: "✅ تم تسيير طلب تقديمك بنجاح! سيتم مراجعته من قبل الاستخبارات وعمداء السيرفر وإبلاغك بالنيابة في أقرب وقت." });
    }

    // B. HR Leave request modal submission
    if (modalId === 'hr_leave_modal') {
      await interaction.deferReply({ ephemeral: true });
      const leaveType = interaction.fields.getTextInputValue('leave_type');
      const leaveReason = interaction.fields.getTextInputValue('leave_reason');

      const leaveEmbed = {
        title: "🌴 طلب إجازة / استقالة إداري جديد",
        description: \`قدّم بواسطة الموظف الإداري: \${interaction.user} (\${interaction.user.tag})\`,
        color: 1752220,
        fields: [
          { name: "🏷️ نوع التماس", value: leaveType, inline: true },
          { name: "📝 شرح الأسباب والظروف والمدة المحددة", value: leaveReason || "غير محدد", inline: false }
        ],
        timestamp: new Date().toISOString()
      };

      const decisionRow = new ActionRowBuilder().addComponents(
        new ButtonBuilder()
          .setCustomId(\`hr_approve_\${interaction.user.id}\`)
          .setLabel("موافق عليها ✅ Accept")
          .setStyle(ButtonStyle.Success),
        new ButtonBuilder()
          .setCustomId(\`hr_reject_\${interaction.user.id}\`)
          .setLabel("مرفوضة ❌ Dismiss")
          .setStyle(ButtonStyle.Danger)
      );

      let hrLogs = interaction.guild.channels.cache.find(c => c.name.includes("إجازة") || c.name.includes("hr"));
      if (!hrLogs) {
        hrLogs = interaction.guild.channels.cache.find(c => c.type === 0);
      }

      if (hrLogs) {
        await hrLogs.send({ embeds: [leaveEmbed], components: [decisionRow] }).catch(console.error);
      }

      return interaction.editReply({ content: "✅ تم إحالة طلب الإجازة الخاص بك لقنوات الهيئة بنجاح ومراجعته جارية فورا!" });
    }
  }
});

// Client login initiation
if (!process.env.DISCORD_TOKEN) {
  console.error("❌ CRITICAL ERROR: DISCORD_TOKEN is missing in your .env file!");
  process.exit(1);
}

client.login(process.env.DISCORD_TOKEN);
`;

  // 5. README.md content with complete explanations
  const readmeMd = `# 🤖 Your Custom Discord Bot: ${config.name}

Congratulations! This project folder includes fully functioning Node.js backend files generated dynamically for your custom Discord application.

This bot includes **all advanced systems** (such as specialized Greeting Cards, Support ticket dispatch, recruitment questionnaires, Security guards filters, Rules categorizations, and leaves Requests) configured directly in your control workbench.

---

## 📁 Package Bundle Contents
- \`index.js\` — Main execution server handling custom Commands, Prefix events, Slash inputs, and modular Embed integrations.
- \`deploy-commands.js\` — Slash deployment registration helper to deploy custom routes into the Discord API scope.
- \`config.json\` — Local profiles (Avatar states, statuses, activity labels, triggers) with complete configurations of advanced systems.
- \`package.json\` — Dependency packages declaration (\`discord.js v14\` + \`@google/genai\`).
- \`.env\` — Private environment variables storage.

---

## 🛠️ Step-by-Step Security Token Configuration

Where to put your Bot Token?
As outlined below, your private bot token goes inside your **\`.env\`** file!

### Step 1: Initialize values inside \`my-discord-bot/.env\`
Open your unzipped folder on your computer, find the \`.env\` file, and modify the target variables:
\`\`\`env
# .env file template
DISCORD_TOKEN="MjYyOT... <-- Paste your Private Discord Bot token here strictly within quotes"
CLIENT_ID="121980...  <-- Paste your client ID (Application ID) here"
GEMINI_API_KEY="AIzaSy... <-- Optional: Your Google Gemini API Key if using AI chat commands"
\`\`\`

### Step 2: Grab Private Secrets from the Discord Developer Portal
1. Load **[Discord Developer Portal](https://discord.com/developers/applications)**.
2. Click **New Application** and enter a name (e.g., \`${config.name}\`).
3. Inside the **Bot** menu:
   - Click **Add Bot** and register it.
   - Click **Reset Token** and copy the private token. **Store this inside your \`.env\` file as \`DISCORD_TOKEN\`!**
   - Scroll down to **Privileged Gateway Intents** and enable:
     - ✅ **Presence Intent**
     - ✅ **Server Members Intent** *(Critical for Greeting welcomes)*
     - ✅ **Message Content Intent** *(Critical for parsing Prefix triggers like \`${config.prefix}\`)*
4. Inside the **OAuth2** menu, fetch your **Client ID** (App ID) and add it to \`.env\` as \`CLIENT_ID\`.

### Step 3: Invite the Bot to Your Server
1. Go to **OAuth2 > URL Generator** in the Developer Portal.
2. Under "Scopes", choose: ✅ **bot** and ✅ **applications.commands**.
3. Under "Bot Permissions", select permissions:
   - ✅ **Administrator** is highly recommended to easily auto-build setup categories, channels, and verify Member roles.
   - If manual: ✅ **Manage Channels**, ✅ **Manage Roles**, ✅ **Send Messages**, ✅ **Embed Links**, ✅ **Manage Messages**.
4. Copy the generated URL at the bottom, paste it into your browser tab, select your target guild, and authorize the bot!

### Step 4: Run the Installation Locally
1. Install **Node.js v18.0.0+** from [nodejs.org](https://nodejs.org).
2. Open your terminal in the bot's root directory and run:
   \`\`\`bash
   npm install
   \`\`\`
3. Deploy the customized slash commands so Discord registers them:
   \`\`\`bash
   npm run deploy
   \`\`\`
4. Start your bot to make it run 24/7!
   \`\`\`bash
   npm start
   \`\`\`

---

## 🛠️ How to Setup Advanced System Boards in Discord

Once your bot has securely logged in and illuminated green inside your server, type the following prefix commands in any target channel as an **Administrator** to deploy the modular boards:

1. **Setup Support Tickets**:
   Type: \`${config.prefix}setup-tickets\` or slash \`/setup-tickets\`
   *Spawns the elegant support support panel. Members can click the button to immediately open a private support channel.*

2. **Setup Recruitment portal**:
   Type: \`${config.prefix}setup-staff\` or slash \`/setup-staff\`
   *Spawns the Recruiter portal button. Clicking it triggers an elegant Discord Modal asking candidate questions. Once submitted, answers are formatted into a rich audit embed in administrative channels so admins can accept/reject candidates with automated DM notifications!*

3. **Setup Verification portal**:
   Type: \`${config.prefix}setup-verify\` or slash \`/setup-verify\`
   *Spawns the security gate verification button. Newcomers click to instantly verify and unlock roles.*

4. **Setup Server Rules**:
   Type: \`${config.prefix}setup-rules\` or slash \`/setup-rules\`
   *Broadcasts organized and beautiful categories of laws.*

5. **Setup HR Leaves**:
   Type: \`${config.prefix}setup-hr\` or slash \`/setup-hr\`
   *Launches leaves, temporary absences, and administrative resignations submissions.*

6. **Setup Reaction Roles Buttons Board (رتب الكبسات التفاعلية)**:
   Type: \`${config.prefix}setup-reactionroles\` or slash \`/setup-reactionroles\`
   *Spawns interactive buttons with styled role lists. Clicking toggles corresponding server roles dynamically!*

7. **Suggestions & Voting Board (نظام الاقتراحات والتصويت التلقائي)**:
   * **Activation**: Simply write your suggestion directly in the configured Suggestions channel.
   * **Bot Behavior**: The bot deletes your plain text message instantly, then posts a beautiful embedded voting board containing upvote (👍) and downvote (👎) interactive reactions.

8. **Auto-Responses System (الردود التلقائية الذكية)**:
   * **Trigger**: Whenever any server member sends a message containing/matching the configured keywords, the bot responds instantly with your preset message templates.

9. **Competitive Levelling System & Leaderboards (نظام مستويات التفاعل والخبرة)**:
   * **Engagement XP**: Sending messages with a 60-second cooldown gives active members experience points.
   * **Role rewards**: Reaching configured levels automatically assigns corresponding role rewards.
   * **Check Rank**: Anyone can type \`${config.prefix}rank\` or \`${config.prefix}level\` to check their levels.

---

## ☁️ Continuous Hosting (Cloud Deployment)
To keep your bot running 24/7 online for free, submit these files to standard services:
- **Render.com / Railway.app / Fly.io**: Link your GitHub repository, configure environment fields (\`DISCORD_TOKEN\`, \`CLIENT_ID\`, \`GEMINI_API_KEY\`), set build command to \`npm install\`, and set start execution shell to \`npm start\`.
`;

  return [
    { filename: "package.json", content: JSON.stringify(packageJson, null, 2), language: "json" },
    { filename: "config.json", content: JSON.stringify(configJson, null, 2), language: "json" },
    { filename: ".env", content: dotenvContent, language: "text" },
    { filename: "deploy-commands.js", content: deployCommandsJs, language: "javascript" },
    { filename: "index.js", content: indexJs, language: "javascript" },
    { filename: "README.md", content: readmeMd, language: "markdown" }
  ];
}
